### ISSUE TITLE
Change WaybackSession’s user-agent string?

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/wayback#11]
`WaybackSession` has inherited its default user-agent string from `web-monitoring-db`: https://github.com/edgi-govdata-archiving/wayback/blob/f1cdb1dc2692b4215f00a2c05c53fe9c733b24f9/wayback/_client.py#L292-L295

That string might not match up so well with this more generic module anymore. Should we change it? If so, I’m thinking something like:

```py
f'python-wayback.WaybackClient/{__version__}'
```

Any thoughts, @danielballan?

**Comment by danielballan** [comment]
I am not well-versed in what conventions user agent strings follow. This seems reasonable to me. Is there any convention for indicating that this is a python package named `wayback` not `python-wayback` as for example `python-dateutil` is? If not, at least this makes it easy enough to find the package by Googling.

**Comment by Mr0grog** [comment]
Outside of web browsers, there’s not really a convention beyond `name[/version]` (at least so far as I’ve ever been aware).

In the HTTP spec, it’s `name[/version][(comment)] name[/version][(comment)] ...`: https://tools.ietf.org/html/rfc7231#section-5.5.3

Good references also at [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) and [Wikipedia](https://en.wikipedia.org/wiki/User_agent), which ultimately say the same thing, just with more info about how nuts browsers get.

> Is there any convention for indicating that this is a python package named wayback not python-wayback as for example python-dateutil is?

So, not really. We could approach it kind of like Googlebot *used* to (IIRC these days it looks more like a browser user agent string):

```
Googlebot/2.1 (+http://www.google.com/bot.html)
```

i.e. something like:

```
wayback/{version} (+https://github.com/edgi-govdata-archiving/wayback)
```

Or we could stuff some of that info into the name:

```
edgi-govdata-archiving.wayback/{version}
# or maybe
envirodgi.wayback/{version}
```

**Comment by danielballan** [comment]
Thanks for the detailed explanation. Mileage may vary, but I find

```
wayback/{version} (+https://github.com/edgi-govdata-archiving/wayback)
```

to be the least ambiguous. If you are happy with that, let's go with it.
