### ISSUE TITLE
Expose and document CdxRecord

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/wayback#4]
`WaybackClient.search()` yields instances of `CdxRecord`, which makes it a public API: https://github.com/edgi-govdata-archiving/wayback/blob/800608fc06a154c5a75442762e0984d0cb72c000/wayback/_client.py#L101-L114

We should at least document it, and probably (?) also expose it publicly.

**I don’t think this is required for the 0.2 release.**

**Comment by danielballan** [comment]
Closed by #5
