### ISSUE TITLE
Consider filtering out repeated results in CDX search

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/wayback#40]
I’m not sure if this is a bug in the Internet Archive’s CDX search right now or if it’s something that was always possible and I just never noticed, but the CDX search endpoint is returning a lot of results where lines are repeated. For example, see the first 4 lines of this query: http://web.archive.org/cdx/search/cdx?url=energystar.gov/&from=20200612

```
gov,energystar)/ 20200612014007 http://energystar.gov/ text/html 301 HLNR6AWVWYCU3YAENY3HYHLIPNWN66X7 432
gov,energystar)/ 20200612014007 http://energystar.gov/ text/html 301 HLNR6AWVWYCU3YAENY3HYHLIPNWN66X7 432
gov,energystar)/ 20200612014014 https://www.energystar.gov/ warc/revisit - DBA3N454ZRZ42QEBER5QRT332DJTTLR5 606
gov,energystar)/ 20200612014014 https://www.energystar.gov/ warc/revisit - DBA3N454ZRZ42QEBER5QRT332DJTTLR5 606
gov,energystar)/ 20200612061543 http://energystar.gov/ text/html 301 HLNR6AWVWYCU3YAENY3HYHLIPNWN66X7 433
gov,energystar)/ 20200612061552 https://www.energystar.gov/ warc/revisit - DBA3N454ZRZ42QEBER5QRT332DJTTLR5 605
...
```

I’ve sent a message over their way to ask what’s up with that, but it seems like it might be worth adding code to filter these out. Even assuming this is accurate (i.e. there actually were two archives made of the same URL in the same second), I’m struggling to think of a scenario where getting both results is really useful.

Care to gut-check me on this, @danielballan?

**Comment by Mr0grog** [comment]
After-the-fact update on this issue: after talking more with the Wayback team, it turns out the duplicate results are almost actually duplicates, not multiple mementos created near simultaneously. They’ve been working on getting more indexes involved in the CDX API so that it can be more up-to-date, but some mementos are listed in multiple indexes, leading to a situation where the same result from two different indexes get listed side-by-side.

So: filtering these out is exactly and unquestionably the correct thing to be doing. :D

**Comment by danielballan** [comment]
Sorry that I arrived at this party too late to be useful. Glad that Wayback provided clarity,
