### ISSUE TITLE
Multiple API endpoints use HTTP instead of HTTPS

### ISSUE THREAD

**Issue by sundhaug92** [edgi-govdata-archiving/wayback#81]
Ex:
- https://github.com/edgi-govdata-archiving/wayback/blob/024a80ec0eae44fcf64e3d834d5f43c78937b8fb/wayback/_models.py#L253
- https://github.com/edgi-govdata-archiving/wayback/blob/024a80ec0eae44fcf64e3d834d5f43c78937b8fb/wayback/_client.py#L48
- https://github.com/edgi-govdata-archiving/wayback/blob/024a80ec0eae44fcf64e3d834d5f43c78937b8fb/wayback/_client.py#L58

Note: Fixing this may require changing the mocks

**Comment by Mr0grog** [comment]
Ah! This is because the memento URLs used to redirect from `https` to `http` (very surprising, which is why I remember it!). It looks like that’s changed, though, so we should probably make everything HTTPS. Thanks! 👍

I’m also happy to accept a PR if you’d like to make the change.
